FROM gradle:latest AS builder
WORKDIR /app
COPY gradlew .
COPY gradle gradle
COPY . .
RUN ./gradlew clean build -x test
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
